package com.aiupworkagent.mobile;

import android.app.Activity;
import android.os.Bundle;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class V11Activity extends Activity {
  static final int INK=Color.rgb(18,28,24), GREEN=Color.rgb(20,92,66), GREEN2=Color.rgb(30,122,88), BG=Color.rgb(247,249,248), BORDER=Color.rgb(225,232,228), MUTED=Color.rgb(101,116,108), PALE=Color.rgb(237,246,241), AMBER=Color.rgb(166,111,0), RED=Color.rgb(167,54,54);
  static final String API="https://ai-upwork-agent-cloud.vercel.app";
  static final String[] STAGES={"Saved","Applied","Reply","Interview","Offer","Won","Lost"};
  SharedPreferences p; LinearLayout page,nav; TextView cloudChip; int tab=0; boolean cloud=false,ai=false; String persistence="database-not-connected"; String lastProposal="",lastTitle=""; int lastScore=0,lastBudget=0;

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(GREEN);getWindow().setNavigationBarColor(Color.WHITE);p=getSharedPreferences("ai_upwork_agent",MODE_PRIVATE);seed();shell();home();status();}
  void seed(){if(!p.contains("headline"))p.edit().putString("headline","PhD Researcher & Academic Manuscript Editor | Journal-Ready Papers").putString("services","Academic research, manuscript editing, literature reviews, dissertation/thesis support, methodology, SPSS/data analysis, business research").putString("evidence","Postgraduate research support; manuscript editing; structured literature reviews; methodology support; quantitative analysis; journal-readiness").putString("preferred","Academic manuscript editing, dissertation support, literature reviews, research methodology, SPSS/data analysis").putString("avoid","Unrelated general writing, unpaid samples, suspicious off-platform requests").putInt("minBudget",100).putInt("hourlyRate",15).apply();}

  void shell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=row();head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(18),dp(15),dp(18),dp(13));head.setBackgroundColor(Color.WHITE);LinearLayout brand=col();TextView t=txt("AI Upwork Agent",22,true);brand.addView(t);TextView s=txt("Opportunity intelligence for your next application",11,false);s.setTextColor(MUTED);brand.addView(s);head.addView(brand,new LinearLayout.LayoutParams(0,-2,1));cloudChip=chip("Checking cloud…",PALE,GREEN);head.addView(cloudChip);root.addView(head);ScrollView sv=new ScrollView(this);page=col();page.setPadding(dp(16),dp(15),dp(16),dp(28));sv.addView(page);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setPadding(dp(6),dp(6),dp(6),dp(6));nav.setBackgroundColor(Color.WHITE);root.addView(nav);setContentView(root);drawNav();}
  void drawNav(){nav.removeAllViews();String[] n={"Home","Brain","Analyze","Tracker","Cloud"};Runnable[] a={this::home,this::brain,this::analyze,this::tracker,this::cloud};for(int i=0;i<n.length;i++){final int x=i;Button b=new Button(this);b.setText(n[i]);b.setAllCaps(false);b.setTextSize(10);b.setTypeface(Typeface.DEFAULT,x==tab?Typeface.BOLD:Typeface.NORMAL);b.setTextColor(x==tab?Color.WHITE:MUTED);b.setBackground(bg(x==tab?GREEN:Color.TRANSPARENT,13,x==tab?GREEN:Color.TRANSPARENT,0));b.setOnClickListener(v->a[x].run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(46),1);lp.setMargins(dp(2),0,dp(2),0);nav.addView(b,lp);}}
  void select(int x){tab=x;drawNav();} void clear(){page.removeAllViews();}

  void home(){select(0);clear();TextView e=txt("YOUR COMMAND CENTRE",10,true);e.setTextColor(GREEN2);page.addView(e);page.addView(txt("Focus on the jobs worth winning.",27,true));TextView i=txt("Qualify faster, spend Connects deliberately, and build proposals from evidence you can defend.",13,false);i.setTextColor(MUTED);i.setPadding(0,dp(5),0,dp(13));page.addView(i);LinearLayout hero=card();hero.setBackground(bg(GREEN,20,GREEN,0));TextView hl=txt("NEXT ACTION",10,true);hl.setTextColor(Color.rgb(190,225,208));hero.addView(hl);TextView ht=txt("Analyze a fresh Upwork opportunity",21,true);ht.setTextColor(Color.WHITE);hero.addView(ht);TextView hs=txt("Get fit, client, pricing, risk and proposal intelligence in one workflow.",12,false);hs.setTextColor(Color.rgb(222,239,231));hero.addView(hs);Button go=button("Analyze Job",Color.WHITE,GREEN,Color.WHITE);go.setOnClickListener(v->analyze());hero.addView(go);page.addView(hero);LinearLayout r1=row();r1.addView(metric("Applications",""+items().size(),"in tracker"),weight());r1.addView(metric("Replies",""+atLeast("Reply"),"responses"),weight());page.addView(r1);LinearLayout r2=row();r2.addView(metric("Interviews",""+atLeast("Interview"),"qualified"),weight());r2.addView(metric("Wins",""+exact("Won"),"contracts"),weight());page.addView(r2);page.addView(label("SYSTEM STATUS"));LinearLayout st=card();st.addView(statusRow("Cloud API",cloud?"Online":"Offline",cloud?GREEN2:RED));st.addView(statusRow("AI engine",ai?"GPT-5.6 Terra live":"Safe fallback",ai?GREEN2:AMBER));st.addView(statusRow("Cloud accounts",persistence.equals("database-not-connected")?"Database pending":"Active",persistence.equals("database-not-connected")?AMBER:GREEN2));page.addView(st);page.addView(label("FREELANCER BRAIN"));page.addView(cardText(p.getString("headline",""),"Reference rate: $"+p.getInt("hourlyRate",15)+"/hr\nMinimum project: $"+p.getInt("minBudget",100)));}

  void brain(){select(1);clear();page.addView(title("Freelancer Brain","This is the evidence base the AI is allowed to use."));EditText h=field("Professional headline",p.getString("headline",""),false),s=field("Services you offer",p.getString("services",""),true),e=field("Evidence / proof you can defend",p.getString("evidence",""),true),pr=field("Jobs to prioritise",p.getString("preferred",""),true),av=field("Jobs / situations to avoid",p.getString("avoid",""),true);LinearLayout r=row();EditText mb=input(""+p.getInt("minBudget",100)),hr=input(""+p.getInt("hourlyRate",15));r.addView(wrap("Minimum budget ($)",mb),weight());r.addView(wrap("Reference rate ($/hr)",hr),weight());page.addView(r);Button save=primary("Save Freelancer Brain");save.setOnClickListener(v->{p.edit().putString("headline",h.getText().toString().trim()).putString("services",s.getText().toString().trim()).putString("evidence",e.getText().toString().trim()).putString("preferred",pr.getText().toString().trim()).putString("avoid",av.getText().toString().trim()).putInt("minBudget",num(mb.getText().toString(),100)).putInt("hourlyRate",num(hr.getText().toString(),15)).apply();hide();Toast.makeText(this,"Freelancer Brain saved on this phone",Toast.LENGTH_SHORT).show();});page.addView(save);LinearLayout note=card();note.setBackground(bg(Color.rgb(250,246,235),16,Color.rgb(235,218,175),1));TextView nh=txt("Truth Guard",14,true);nh.setTextColor(AMBER);note.addView(nh);TextView np=txt("If the client asks for experience that is not stored here, live AI should flag the gap instead of inventing it.",12,false);np.setTextColor(Color.rgb(105,82,33));note.addView(np);page.addView(note);}

  void analyze(){select(2);clear();page.addView(title("Analyze Job","Paste the actual Upwork brief. Cloud intelligence is used when available; safe fallback remains built in."));EditText jt=field("Job title","Academic Manuscript Editor for Journal Submission",false),jd=field("Job description","We need an experienced academic editor to improve two research manuscripts for peer-reviewed journal submission. Strengthen clarity, structure, references and overall journal readiness.",true);LinearLayout r=row();EditText bu=input("500"),co=input("12");r.addView(wrap("Budget ($)",bu),weight());r.addView(wrap("Connects required",co),weight());page.addView(r);EditText cl=field("Client details","Payment verified, 76% hire rate, $26k spend, good reviews",true);LinearLayout m=card();m.addView(statusRow("Analysis mode",ai?"Live GPT-5.6 Terra":"Cloud/local fallback",ai?GREEN2:AMBER));page.addView(m);Button run=primary("Build Opportunity Report");run.setOnClickListener(v->{String t=jt.getText().toString().trim(),d=jd.getText().toString().trim();if(t.isEmpty()||d.isEmpty()){Toast.makeText(this,"Add a job title and description",Toast.LENGTH_SHORT).show();return;}hide();run.setEnabled(false);run.setText("Analyzing opportunity…");runAnalysis(t,d,num(bu.getText().toString(),0),num(co.getText().toString(),0),cl.getText().toString().trim(),run);});page.addView(run);}

  void runAnalysis(String t,String d,int b,int c,String cl,Button btn){new Thread(()->{try{JSONObject job=new JSONObject().put("title",t).put("description",d).put("budget",b).put("connects",c).put("clientDetails",cl);JSONObject body=new JSONObject().put("job",job).put("brain",brainJson());JSONObject res=post(API+"/api/analyze",body);JSONObject a=res.getJSONObject("analysis");String mode=res.optString("mode","fallback");runOnUiThread(()->report(t,b,mode,a));}catch(Exception ex){JSONObject a=local(t,d,b,c,cl);runOnUiThread(()->{Toast.makeText(this,"Cloud unavailable — using safe local analysis",Toast.LENGTH_SHORT).show();report(t,b,"device-fallback",a);});}finally{runOnUiThread(()->{btn.setEnabled(true);btn.setText("Build Opportunity Report");});}}).start();}

  void report(String t,int budget,String mode,JSONObject a){lastTitle=t;lastBudget=budget;lastScore=a.optInt("opportunityScore");lastProposal=a.optString("proposal");clear();page.addView(title("Opportunity Report",t));LinearLayout sc=card();sc.setBackground(bg(INK,20,INK,0));LinearLayout top=row();LinearLayout l=col();TextView sv=txt(lastScore+"/100",37,true);sv.setTextColor(Color.WHITE);l.addView(sv);TextView sl=txt("Opportunity score",11,false);sl.setTextColor(Color.rgb(194,205,199));l.addView(sl);top.addView(l,new LinearLayout.LayoutParams(0,-2,1));top.addView(chip(a.optString("recommendation","CONSIDER"),lastScore>=74?Color.rgb(213,242,227):Color.rgb(250,232,190),lastScore>=74?GREEN:AMBER));sc.addView(top);TextView md=txt(mode.equals("live-ai")?"Live AI analysis · GPT-5.6 Terra":"Safe fallback analysis",11,true);md.setTextColor(mode.equals("live-ai")?Color.rgb(135,221,180):Color.rgb(236,204,130));md.setPadding(0,dp(12),0,0);sc.addView(md);page.addView(sc);LinearLayout mr=row();mr.addView(metric("Client",a.optInt("clientQuality")+"/10","quality"),weight());mr.addView(metric("Suggested bid","$"+a.optInt("suggestedBid"),"starting point"),weight());page.addView(mr);page.addView(cardText("Fit Summary",a.optString("fitSummary")));page.addView(cardText("What the client really needs",a.optString("clientNeed")));page.addView(cardText("Winning angle",a.optString("winningAngle")));page.addView(cardText("Connects decision",a.optString("connectsDecision")));JSONArray miss=a.optJSONArray("missingEvidence");if(miss!=null&&miss.length()>0){LinearLayout w=card();w.setBackground(bg(Color.rgb(253,244,242),16,Color.rgb(240,204,198),1));TextView wh=txt("Evidence gaps — do not invent these",14,true);wh.setTextColor(RED);w.addView(wh);for(int i=0;i<miss.length();i++){TextView x=txt("• "+miss.optString(i),12,false);x.setTextColor(Color.rgb(110,61,54));w.addView(x);}page.addView(w);}page.addView(label("PROPOSAL"));page.addView(cardText("Ready-to-review draft",lastProposal));page.addView(cardText("Best question to ask",a.optString("bestQuestion")));Button copy=primary("Copy Proposal");copy.setOnClickListener(v->{((ClipboardManager)getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("proposal",lastProposal));Toast.makeText(this,"Proposal copied",Toast.LENGTH_SHORT).show();});page.addView(copy);Button save=secondary("Add to Application Tracker");save.setOnClickListener(v->{add(lastTitle,lastScore,lastBudget,"Saved");Toast.makeText(this,"Added to tracker",Toast.LENGTH_SHORT).show();});page.addView(save);Button again=secondary("Analyze Another Job");again.setOnClickListener(v->analyze());page.addView(again);}

  void tracker(){select(3);clear();page.addView(title("Application Tracker","Move each opportunity through the real outcome stages so we can learn what converts."));List<String[]> xs=items();if(xs.isEmpty()){LinearLayout e=card();e.addView(txt("No applications yet",18,true));TextView q=txt("Analyze a job, review the report, then save the opportunity here.",12,false);q.setTextColor(MUTED);e.addView(q);Button b=primary("Analyze a Job");b.setOnClickListener(v->analyze());e.addView(b);page.addView(e);return;}for(int i=0;i<xs.size();i++){final int k=i;String[] x=xs.get(i);LinearLayout c=card();LinearLayout h=row();TextView n=txt(x[0],15,true);h.addView(n,new LinearLayout.LayoutParams(0,-2,1));h.addView(chip(x[1]+"/100",PALE,GREEN));c.addView(h);TextView meta=txt("Budget $"+x[2]+"  •  "+x[3],12,true);meta.setTextColor(MUTED);meta.setPadding(0,dp(8),0,dp(8));c.addView(meta);int si=stage(x[3]);Button next=secondary(si<STAGES.length-1?"Move to "+STAGES[si+1]:"Completed");next.setEnabled(si<STAGES.length-1);next.setOnClickListener(v->{List<String[]> now=items();if(k<now.size()){int z=stage(now.get(k)[3]);if(z<STAGES.length-1)now.get(k)[3]=STAGES[z+1];saveItems(now);tracker();}});c.addView(next);page.addView(c);}}

  void cloud(){select(4);clear();page.addView(title("Account & Cloud","See exactly what is real, local, and still waiting for infrastructure."));page.addView(label("CONNECTIONS"));LinearLayout c=card();c.addView(statusRow("Cloud API",cloud?"Online":"Offline",cloud?GREEN2:RED));c.addView(statusRow("AI Gateway",ai?"Live":"Not activated",ai?GREEN2:AMBER));c.addView(statusRow("Model","GPT-5.6 Terra",GREEN));c.addView(statusRow("Account database",persistence.equals("database-not-connected")?"Not connected":"Active",persistence.equals("database-not-connected")?AMBER:GREEN2));c.addView(statusRow("Upwork OAuth","Planned next phase",MUTED));page.addView(c);EditText em=field("Email for future cloud account",p.getString("accountEmail",""),false);Button se=secondary("Save Email on Device");se.setOnClickListener(v->{p.edit().putString("accountEmail",em.getText().toString().trim()).apply();Toast.makeText(this,"Saved locally. Cloud sync still needs the database.",Toast.LENGTH_LONG).show();});page.addView(se);LinearLayout n=card();n.setBackground(bg(Color.rgb(244,247,255),16,Color.rgb(213,222,244),1));TextView h=txt("Cloud account status",14,true);h.setTextColor(Color.rgb(52,74,131));n.addView(h);TextView q=txt("Sign-in and cross-device sync will become real only after a persistent database is connected. Until then, your Brain and tracker remain on this phone.",12,false);q.setTextColor(Color.rgb(68,82,120));n.addView(q);page.addView(n);Button rf=primary("Refresh Cloud Status");rf.setOnClickListener(v->status());page.addView(rf);}

  void status(){new Thread(()->{try{JSONObject s=get(API+"/api/status");cloud=s.optBoolean("ok");ai=s.optBoolean("ai");persistence=s.optString("persistence","database-not-connected");}catch(Exception e){cloud=false;ai=false;}runOnUiThread(()->{cloudChip.setText(cloud?(ai?"AI live":"Cloud online"):"Offline");cloudChip.setTextColor(cloud?GREEN:RED);cloudChip.setBackground(bg(cloud?PALE:Color.rgb(253,237,234),999,cloud?Color.rgb(207,230,218):Color.rgb(242,205,198),1));if(tab==0)home();if(tab==4)cloud();});}).start();}

  JSONObject brainJson()throws Exception{return new JSONObject().put("headline",p.getString("headline","")).put("services",p.getString("services","")).put("evidence",p.getString("evidence","")).put("preferredJobs",p.getString("preferred","")).put("avoid",p.getString("avoid","")).put("minBudget",p.getInt("minBudget",100)).put("hourlyRate",p.getInt("hourlyRate",15));}
  JSONObject get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("GET");c.setConnectTimeout(8000);c.setReadTimeout(12000);return read(c);} JSONObject post(String u,JSONObject j)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setConnectTimeout(10000);c.setReadTimeout(60000);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream o=c.getOutputStream()){o.write(j.toString().getBytes(StandardCharsets.UTF_8));}return read(c);} JSONObject read(HttpURLConnection c)throws Exception{int s=c.getResponseCode();BufferedReader b=new BufferedReader(new InputStreamReader(s>=400?c.getErrorStream():c.getInputStream(),StandardCharsets.UTF_8));StringBuilder x=new StringBuilder();String l;while((l=b.readLine())!=null)x.append(l);b.close();if(s>=400)throw new Exception("Cloud error "+s);return new JSONObject(x.toString());}
  JSONObject local(String t,String d,int b,int co,String cl){JSONObject a=new JSONObject();try{String h=(t+" "+d).toLowerCase(Locale.ROOT);int s=46;for(String w:new String[]{"research","academic","manuscript","journal","thesis","dissertation","literature","spss","methodology","analysis"})if(h.contains(w))s+=4;if(b>=p.getInt("minBudget",100))s+=8;else s-=8;if(cl.toLowerCase(Locale.ROOT).contains("verified"))s+=5;if(co<=12)s+=3;if(co>20)s-=8;s=Math.max(0,Math.min(95,s));a.put("opportunityScore",s).put("recommendation",s>=88?"STRONG APPLY":s>=74?"APPLY":s>=60?"CONSIDER":"SKIP").put("clientQuality",cl.toLowerCase(Locale.ROOT).contains("verified")?8:5).put("fitSummary","Local fallback analysis based on the job, budget and saved Freelancer Brain.").put("clientNeed","A reliable specialist who can deliver the requested outcome with clear evidence of fit.").put("winningAngle",p.getString("headline","Lead with your closest evidence.")).put("suggestedBid",Math.max(p.getInt("minBudget",100),b>0?Math.round(b*.9f):150)).put("connectsDecision",s>=74&&co<=16?"Worth spending":"Be selective").put("missingEvidence",new JSONArray()).put("proposal","I read your brief with the final outcome in mind. My relevant positioning is "+p.getString("headline","research support")+". The closest evidence I can support is "+p.getString("evidence","the experience saved in my Freelancer Brain")+".\n\nI would begin by identifying the highest-impact requirements, complete the core work against those requirements, and finish with a focused quality-assurance pass.\n\nWhat is the most important outcome you want from this engagement?").put("bestQuestion","What is the single most important outcome you want from this engagement?");}catch(Exception ignored){}return a;}

  void add(String t,int s,int b,String st){List<String[]>x=items();x.add(0,new String[]{clean(t),""+s,""+b,st});saveItems(x);} List<String[]> items(){List<String[]>o=new ArrayList<>();String r=p.getString("tracker","");if(r==null||r.isEmpty())return o;for(String z:r.split("\\u001e")){String[]c=z.split("\\u001f",-1);if(c.length==4)o.add(c);}return o;} void saveItems(List<String[]>x){StringBuilder b=new StringBuilder();for(int i=0;i<x.size();i++){if(i>0)b.append('\u001e');String[]z=x.get(i);b.append(clean(z[0])).append('\u001f').append(z[1]).append('\u001f').append(z[2]).append('\u001f').append(z[3]);}p.edit().putString("tracker",b.toString()).apply();} String clean(String s){return s.replace("\u001e"," ").replace("\u001f"," ");} int exact(String s){int n=0;for(String[]x:items())if(x[3].equals(s))n++;return n;} int atLeast(String s){int t=stage(s),n=0;for(String[]x:items()){int i=stage(x[3]);if(i>=t&&!x[3].equals("Lost"))n++;}return n;} int stage(String s){for(int i=0;i<STAGES.length;i++)if(STAGES[i].equals(s))return i;return 0;}

  TextView txt(String s,int z,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(INK);t.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);t.setLineSpacing(0,1.12f);return t;} TextView chip(String s,int bg,int fg){TextView t=txt(s,10,true);t.setTextColor(fg);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),dp(6),dp(10),dp(6));t.setBackground(bg(bg,999,bg,0));return t;} TextView label(String s){TextView t=txt(s,10,true);t.setTextColor(MUTED);t.setPadding(dp(2),dp(12),0,dp(7));return t;}
  LinearLayout title(String h,String s){LinearLayout c=col();c.setPadding(0,0,0,dp(10));c.addView(txt(h,25,true));TextView p=txt(s,12,false);p.setTextColor(MUTED);p.setPadding(0,dp(4),0,0);c.addView(p);return c;} LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;} LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;} LinearLayout card(){LinearLayout c=col();c.setPadding(dp(15),dp(15),dp(15),dp(15));c.setBackground(bg(Color.WHITE,18,BORDER,1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(0,dp(5),0,dp(7));c.setLayoutParams(q);return c;} LinearLayout metric(String a,String b,String c){LinearLayout m=card();m.setPadding(dp(13),dp(13),dp(13),dp(13));m.addView(txt(b,26,true));TextView l=txt(a,11,true);l.setTextColor(GREEN);m.addView(l);TextView n=txt(c,9,false);n.setTextColor(MUTED);m.addView(n);return m;} LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(3),dp(3),dp(3),dp(3));return p;} LinearLayout cardText(String h,String s){LinearLayout c=card();c.addView(txt(h,15,true));TextView b=txt(s,12,false);b.setTextColor(MUTED);b.setPadding(0,dp(7),0,0);c.addView(b);return c;} LinearLayout statusRow(String a,String b,int color){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(6),0,dp(6));r.addView(txt(a,12,true),new LinearLayout.LayoutParams(0,-2,1));TextView s=txt(b,11,true);s.setTextColor(color);r.addView(s);return r;}
  EditText field(String l,String v,boolean multi){TextView x=txt(l,11,true);x.setTextColor(MUTED);x.setPadding(dp(2),dp(7),0,dp(5));page.addView(x);EditText e=input(v);e.setSingleLine(!multi);if(multi)e.setMinLines(4);page.addView(e);return e;} EditText input(String v){EditText e=new EditText(this);e.setText(v);e.setTextSize(13);e.setTextColor(INK);e.setPadding(dp(13),dp(11),dp(13),dp(11));e.setBackground(bg(Color.WHITE,13,BORDER,1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(0,0,0,dp(7));e.setLayoutParams(q);return e;} LinearLayout wrap(String l,EditText e){LinearLayout c=col();TextView x=txt(l,10,true);x.setTextColor(MUTED);x.setPadding(dp(2),dp(6),0,dp(5));c.addView(x);c.addView(e);return c;}
  Button primary(String s){return button(s,GREEN,Color.WHITE,GREEN);} Button secondary(String s){return button(s,Color.WHITE,GREEN,BORDER);} Button button(String s,int bg,int fg,int st){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(12);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(fg);b.setBackground(bg(bg,13,st,st==bg?0:1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(50));q.setMargins(0,dp(6),0,dp(4));b.setLayoutParams(q);return b;} GradientDrawable bg(int f,int r,int s,int w){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(dp(r));if(w>0)d.setStroke(dp(w),s);return d;} int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} int num(String s,int f){try{return Integer.parseInt(s.trim());}catch(Exception e){return f;}} void hide(){View v=getCurrentFocus();if(v!=null)((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);}
}
